# Generated by Django 3.2 on 2021-04-22 11:44

import ckeditor.fields
import datetime
from django.db import migrations
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journal_app', '0003_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=datetime.datetime(2021, 4, 22, 11, 44, 55, 231898, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
